spring.application.name=springrest

server.port=8085

#jdbc sql config
spring.datasource.url=jdbc:mysql://localhost:3306/springrest
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.security.user.name=admin
spring.security.user.password=admin123

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG


#env file

jwt.rsa.public-key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlc2oMtgWLuMDta/qXolPPy+tqAX3PjlfvDIc8aYVHzD6DTQZN0PKKKI78uNZJFekTTm0xJnAhRCiD11fYjvBmbmyI0Jsr4pxDyUHgGFPrg8Su54hN3UmeQyD8sSKmszeRptamrFmSzSrSUOdb4Bv/eP/OmgVcJ5mxrS0t2mWqATCnWOv3Sx0TjXiJW7cWNsDnfp2Rahh0ZTtm94t7F2OrI+oNiOAFhpY1xfuTLTyK9n5ntx0tEjILlJ3E0p1EpUJK+K59bgwu1HCdT34PkXPKgFPfL8L/c0vK51RBFjXskguSTpjV4H4a3ixYCoPXwN6sDFW5L2bvzWKqZlvEoLkiwIDAQAB


