spring.application.name=springrest

server.port=8085

#jdbc sql config
spring.datasource.url=jdbc:mysql://localhost:3306/springrest
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect



#env file

jwt.secret=qLqUY7xv9Hj41H0saKviOXq/4eLG7tYp1mQF4H8abCDlG9tJpN9YpYHYrU0s0u4d=



